#!/bin/bash

(( BASHIN ))||{ # setup bashin (framework) if not found on system
  bash <(curl -s https://raw.githubusercontent.com/wick3dr0se/bashin/main/setup.sh)
}

import std/tui # term_size

init_term(){
  term_size
  ((ROWS=LINES-2)); ((SPOS=ROWS+1))

  printf '\e[?1049h\e[?25l\e[?7l'
}

end(){
  printf '\e[?1049l\e[?25h\e[?7h'
  exit
}

read_keys(){
  read -rsn1
  [[ $REPLY == $'\e' ]]&& read -rsn2
  KEY="${REPLY^^}"
}

get_files(){
  unset STACK

  for _ in *; do
    if [[ -h $_ ]]; then
      push "\e[36m$_\e[m@"
    elif [[ -d $_ ]]; then
      push "\e[34m$_\e[m/"
    elif [[ -x $_ ]]; then
      push "\e[32m$_\e[m*"
    else
      push "\e[39m$_\e[m"
    fi
  done

  draw_files
}

draw_files(){
  cursor="${1:-$ROWS}"

  unset SKIP N hoverHist

  printf '\e[2J'

  for _ in "${!STACK[@]}"; do
    (( _ < ROWS ))&& printf '\e[%dH\e[2m%b' "$((ROWS-_))" "${STACK[$_]}"
  done
}

open_file(){
  controls='[<]back [^]exec [>]edit'

  printf '\e[?1049l\e[2J\e[3J\e[H\e[?7l'

  mapfile -tn 1000 <"$1"
  printf '%s\n' "${MAPFILE[@]}"

  printf '\e[S'

  hud
  unset controls

  for((;;)){
    read_keys
    case $KEY in
      Q) end;;
      H|\[D) draw_files; break;;
      K|\[A)
        if [[ -x $1 ]]; then
          "$PWD/$1"
        else
          bash "$1"
        fi
      ;;
      L|\[C) "${EDITOR:-${VISUAL:-vi}}" "$1";;
    esac
  }

  printf '\e[2J\e[3J\e[?1049h\e[?25l'
  draw_files
}

open_dir(){
  cd "$1"|| return
  
  get_files
}

hidden_toggle(){
  if shopt -p dotglob; then
    shopt -u dotglob
  else
    shopt -s dotglob
  fi

  get_files
}

hover(){
  (( pause ))||{
    HOVER="${STACK[$ROWS-$1]}"
    printf '\e[%dH\e[7m%b' "$1" "$HOVER"

    (( ${#STACK[@]} > 1 ))&&{
      hoverHist+=("\e[${1}H$HOVER")
      skip&&{
        printf '%b' "${hoverHist[0]}"
        hoverHist=("${hoverHist[@]:1}")
      }
    }
  }; pause=0
}

scrollback(){
  if (( ${#STACK[@]} > ROWS )); then
    if (( cursor > ROWS )); then
      cycle "-$ROWS"
      draw_files 1
    elif (( cursor < 1 )); then
      cycle "$ROWS"
      draw_files
    fi
  else
    if (( cursor > ROWS )); then
      ((cursor=SPOS-${#STACK[@]}))
    elif (( cursor < SPOS-${#STACK[@]} )); then
      cursor="$ROWS"
    fi
  fi
}

hud(){
  printf '\e[%dH\e[2K\e[44mFML\e[m %b %b\e[%dH%s %s' \
    "$SPOS" "$HOVER" "${stats-}" \
    "$LINES" "${controls:=[<]back [>]open}" "$PWD"
}

init_term
get_files
for((;;)){
  hover "$cursor"

  hud

  read_keys
  case $KEY in
    Q) end;;
    H|\[D) cd ../; get_files;;
    J|\[B) ((cursor++));;
    K|\[A) ((cursor--));;
    L|\[C)
      : "${HOVER#\\e[3?m}"
      selected="${_%\\e*}"

      stats="\e[33mMarked\e[m: $PWD/$HOVER"
      
      if [[ -d $selected ]]; then
        open_dir "$selected"
      elif [[ -f $selected ]]; then
        open_file "$selected"
      fi
    ;;
    .) hidden_toggle;;
    *) pause=1;;
  esac

  scrollback
}
