#!/bin/bash

term_init(){
  shopt -s checkwinsize; (:;:)
  printf '\e[?1049h\e[2J\e[?25l\e[?7l\e[999H'
  ((rows=LINES-1))
}

read_keys(){
  read -rsn1; [[ $REPLY == $'\e' ]]&& read -rsn2
  KEY="${REPLY^^}"
}

status_bar(){
  printf '\e[999H\e[2K\e[1;41;30mFML\e[m%s' "${1:+: $1}"
}

infinite_scroll(){
  if (( ${#filesB[@]} > rows )); then
    if (( cursor < LINES-${#files[@]} )); then
      cursor="$rows"
    elif (( cursor > rows )); then
      cursor=1
      files=("${filesB[@]:0:${#files[@]}+$rows}")
      draw_files
    elif (( cursor < 1 )); then
      cursor="$rows"
      files=("${files[@]:0:${#files[@]}-$rows}")
      draw_files
    fi
  else
    if (( cursor > rows )); then
      ((cursor=LINES-${#files[@]}))
    elif (( cursor < LINES-${#files[@]} )); then
      cursor="$rows"
    fi
  fi

  printf '\e[%dH' "$cursor"
}

hover_file(){
  hover="${files[cursor-LINES]:-}"
  hist+=("${cursor}H\e[3${hover}")
  (( ${i:=0} ))&&{
    printf '\e[%b\e[m' "${hist[0]}"
    hist=("${hist[@]:1}")
  }|| i=1

  printf '\e[%dH\e[1;4%b' "$cursor" "$hover"
}

hidden_toggle(){
  if shopt -p dotglob; then
    shopt -u dotglob
  else
    shopt -s dotglob
  fi

  get_files; status_bar
}

get_files(){
  unset files

  for _ in *; do
    if [[ $_ == '*' ]]; then
      files=('9mempty')
    elif [[ -h $_ ]]; then
      files+=("3m$_\e[m")
    elif [[ -d $_ ]]; then
      files+=("4m$_\e[m")
    elif [[ -x $_|| $_ == *'.sh' ]]; then
      files+=("2m$_\e[m")
    else
      files+=("9m$_\e[m")
    fi
  done

  filesB=("${files[@]}")
  draw_files
}

draw_files(){
  unset i hist
  
  printf '\e[2J\e[999H'
  printf '\e[3%b\n' "${files[@]}"
  
  status_bar "$selected"
}

files_selected(){
  if [[ -d "$1" ]]; then
    if cd "$1" 2>/dev/null; then
      cursor="$rows"; get_files; status_bar "$1"
    else
      status_bar
    fi
  elif [[ -f "$1" ]]; then
    printf '\e[?1049l\e[2J\e[999H'
    file_read "$1"
    
    status_bar "$1"; file_keymap
  fi
}

file_read(){
  mapfile -tn 250 <"$1"
  printf '%s\n' "${MAPFILE[@]}"
}

file_keymap(){
  for((;;)){
    read_keys
    case $KEY in
      H|\[D) printf '\e[?1049h\e[?25l\e[?7l'; get_files; status_bar; break;;
      L|\[C) "${EDITOR:-${VISUAL:-vim}}" "$selected"
    esac
  }
}

main_keymap(){
  read_keys
  case $KEY in
    Q) printf '\e[?1049l\e[?25h\e[?7h'; exit;;
    A) hidden_toggle;;
    H|\[D) cursor="$rows"; cd ../; get_files; status_bar;;
    J|\[B) ((cursor++));;
    K|\[A) ((cursor--));;
    L|\[C) selected="${files[cursor-LINES]#*[0-9]m}" selected="${selected%\\e*}"
      
      status_bar "$selected"; files_selected "$selected"
    ;;
  esac
}

trap 'printf "\e[?1049l\e[?25h\e[?7h"; exit' INT
trap 'term_init; get_files; status_bar' WINCH

term_init; cursor="$rows"
get_files; hover_file; status_bar
for((;;)){ main_keymap; infinite_scroll; hover_file; }